"""Pure data: seed sites and search queries.

No side effects, no imports beyond models.  Easy to extend by appending
to the two lists below.
"""
from __future__ import annotations

from db.models import Site, Zone, SiteType

SEED_SITES: tuple[Site, ...] = (
    # ── Portales inmobiliarios principales ─────────────────────────────
    # Idealista removed: aggressive CAPTCHA blocks headless scraping (0 chars always)
    Site(url="https://www.fotocasa.es/es/obra-nueva/viviendas/madrid-capital/todas-las-zonas/l",
         name="Fotocasa Obra Nueva Madrid", zone=Zone.TODAS, site_type=SiteType.PORTAL),
    Site(url="https://www.pisos.com/obra-nueva/pisos-madrid/",
         name="Pisos.com Obra Nueva Madrid", zone=Zone.TODAS, site_type=SiteType.PORTAL),
    Site(url="https://www.yaencontre.com/obra-nueva/pisos/madrid",
         name="YaEncontre Obra Nueva", zone=Zone.TODAS, site_type=SiteType.PORTAL),
    Site(url="https://www.tucasa.com/obra-nueva/madrid/",
         name="TuCasa Obra Nueva", zone=Zone.TODAS, site_type=SiteType.PORTAL),
    Site(url="https://www.hogaria.net/obra-nueva/madrid/",
         name="Hogaria Obra Nueva", zone=Zone.TODAS, site_type=SiteType.PORTAL),
    Site(url="https://www.obranuevaenmadrid.es/",
         name="Obra Nueva en Madrid", zone=Zone.TODAS, site_type=SiteType.PORTAL),
    Site(url="https://www.enalquiler.com/obra-nueva/madrid/",
         name="EnAlquiler Obra Nueva", zone=Zone.TODAS, site_type=SiteType.PORTAL),
    Site(url="https://www.solvia.es/es/obra-nueva/viviendas/madrid/",
         name="Solvia Obra Nueva Madrid", zone=Zone.TODAS, site_type=SiteType.PORTAL),
    # ── Plataformas de cooperativas ────────────────────────────────────
    Site(url="https://cooptima.es/cooperativas-de-viviendas/madrid",
         name="Cooptima Madrid", zone=Zone.TODAS, site_type=SiteType.COOPERATIVA),
    Site(url="https://aurora-homes.es/cooperativas-de-viviendas-en-madrid/",
         name="Aurora Homes", zone=Zone.TODAS, site_type=SiteType.COOPERATIVA),
    Site(url="https://concovi.org/",
         name="CONCOVI", zone=Zone.TODAS, site_type=SiteType.COOPERATIVA),
    Site(url="https://www.grupovia.net/",
         name="Grupo Via", zone=Zone.TODAS, site_type=SiteType.COOPERATIVA),
    Site(url="https://www.lacooperativadecaballeromejor.com/",
         name="Cooperativa Caballero Mejor", zone=Zone.TODAS, site_type=SiteType.COOPERATIVA),
    Site(url="https://www.dfrente.es/",
         name="DFrente Cooperativa", zone=Zone.TODAS, site_type=SiteType.COOPERATIVA),
    Site(url="https://www.larcovi.com/",
         name="Larcovi Cooperativas", zone=Zone.TODAS, site_type=SiteType.COOPERATIVA),
    Site(url="https://www.ibosa.es/",
         name="Ibosa Group", zone=Zone.TODAS, site_type=SiteType.COOPERATIVA),
    Site(url="https://www.juntacompensacion.es/",
         name="Junta Compensacion", zone=Zone.TODAS, site_type=SiteType.COOPERATIVA),
    # ── Constructoras / Promotoras ─────────────────────────────────────
    Site(url="https://www.aelca.es/viviendas/madrid/",
         name="Aelca Madrid", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.metrovacesa.com/promociones-obra-nueva/madrid",
         name="Metrovacesa Madrid", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.neinorhomes.com/promociones/madrid/",
         name="Neinor Homes Madrid", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.viacelere.com/obra-nueva/madrid",
         name="Via Celere Madrid", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.habitatinmobiliaria.com/viviendas/madrid/",
         name="Habitat Inmobiliaria", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.arpada.es/promociones/",
         name="Arpada Promociones", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.amenabar.com/promociones-madrid/",
         name="Amenabar Madrid", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.kronos-homes.com/es/promociones/?city=madrid",
         name="Kronos Homes Madrid", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.aedashomes.com/promociones/madrid/",
         name="AEDAS Homes Madrid", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.pryconsa.es/viviendas/madrid/",
         name="Pryconsa Madrid", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.librehomes.com/",
         name="Libre Homes", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.gestilar.com/promociones-viviendas/madrid/",
         name="Gestilar Madrid", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.culmiaresidencial.com/es/promociones?province=madrid",
         name="Culmia Madrid", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.quabitinmobiliaria.com/promociones/madrid",
         name="Quabit Madrid", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.larimarproyectos.com/",
         name="Larimar Proyectos", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.stoneweg.com/es/proyectos/",
         name="Stoneweg Living", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    Site(url="https://www.gilmargroup.com/es/obra-nueva/madrid/",
         name="Gilmar Obra Nueva", zone=Zone.TODAS, site_type=SiteType.CONSTRUCTORA),
    # ── Portales VPO / vivienda protegida ──────────────────────────────
    Site(url="https://www.comunidad.madrid/servicios/vivienda/vivienda-proteccion-publica",
         name="CAM Vivienda Protegida", zone=Zone.TODAS, site_type=SiteType.PORTAL),
    Site(url="https://www.emvs.es/Paginas/home.aspx",
         name="EMVS Madrid", zone=Zone.TODAS, site_type=SiteType.PORTAL),
    # ── Zonas especificas norte ────────────────────────────────────────
    Site(url="https://www.idealista.com/obra-nueva/alcobendas/",
         name="Idealista Alcobendas", zone=Zone.NORTE, site_type=SiteType.PORTAL),
    Site(url="https://www.idealista.com/obra-nueva/san-sebastian-de-los-reyes/",
         name="Idealista S.S. Reyes", zone=Zone.NORTE, site_type=SiteType.PORTAL),
    Site(url="https://www.idealista.com/obra-nueva/tres-cantos/",
         name="Idealista Tres Cantos", zone=Zone.NORTE, site_type=SiteType.PORTAL),
    Site(url="https://www.idealista.com/obra-nueva/colmenar-viejo/",
         name="Idealista Colmenar Viejo", zone=Zone.NORTE, site_type=SiteType.PORTAL),
    # ── Zonas especificas este ─────────────────────────────────────────
    Site(url="https://www.idealista.com/obra-nueva/torrejon-de-ardoz/",
         name="Idealista Torrejon", zone=Zone.ESTE, site_type=SiteType.PORTAL),
    Site(url="https://www.idealista.com/obra-nueva/coslada/",
         name="Idealista Coslada", zone=Zone.ESTE, site_type=SiteType.PORTAL),
    Site(url="https://www.idealista.com/obra-nueva/rivas-vaciamadrid/",
         name="Idealista Rivas", zone=Zone.ESTE, site_type=SiteType.PORTAL),
    Site(url="https://www.idealista.com/obra-nueva/alcala-de-henares/",
         name="Idealista Alcala Henares", zone=Zone.ESTE, site_type=SiteType.PORTAL),
    Site(url="https://www.idealista.com/obra-nueva/arganda-del-rey/",
         name="Idealista Arganda", zone=Zone.ESTE, site_type=SiteType.PORTAL),
    # ── Zonas especificas oeste ────────────────────────────────────────
    Site(url="https://www.idealista.com/obra-nueva/pozuelo-de-alarcon/",
         name="Idealista Pozuelo", zone=Zone.OESTE, site_type=SiteType.PORTAL),
    Site(url="https://www.idealista.com/obra-nueva/majadahonda/",
         name="Idealista Majadahonda", zone=Zone.OESTE, site_type=SiteType.PORTAL),
    Site(url="https://www.idealista.com/obra-nueva/boadilla-del-monte/",
         name="Idealista Boadilla", zone=Zone.OESTE, site_type=SiteType.PORTAL),
    Site(url="https://www.idealista.com/obra-nueva/las-rozas-de-madrid/",
         name="Idealista Las Rozas", zone=Zone.OESTE, site_type=SiteType.PORTAL),
    Site(url="https://www.idealista.com/obra-nueva/villanueva-de-la-canada/",
         name="Idealista Villanueva Canada", zone=Zone.OESTE, site_type=SiteType.PORTAL),
    Site(url="https://www.idealista.com/obra-nueva/villaviciosa-de-odon/",
         name="Idealista Villaviciosa", zone=Zone.OESTE, site_type=SiteType.PORTAL),
)

SEARCH_QUERIES: tuple[dict[str, str], ...] = (
    # ── Cooperativas por zona ──────────────────────────────────────────
    {"query": "cooperativa vivienda Madrid norte Alcobendas Tres Cantos 2025 2026", "zone": "norte"},
    {"query": "cooperativa vivienda Madrid este Rivas Torrejon Coslada 2025 2026", "zone": "este"},
    {"query": "cooperativa vivienda Madrid oeste Pozuelo Majadahonda Las Rozas 2025 2026", "zone": "oeste"},
    {"query": "cooperativa vivienda nueva Madrid 2026 inscripcion", "zone": "todas"},
    {"query": "cooperativas viviendas Madrid abierta inscripcion socios", "zone": "todas"},
    {"query": "cooperativa pisos Madrid precio asequible joven", "zone": "todas"},
    # ── Obra nueva por zona ────────────────────────────────────────────
    {"query": "obra nueva pisos Madrid norte Alcobendas San Sebastian Reyes", "zone": "norte"},
    {"query": "obra nueva pisos Madrid este Torrejon Coslada Alcala Henares", "zone": "este"},
    {"query": "obra nueva pisos Madrid oeste Pozuelo Boadilla Las Rozas", "zone": "oeste"},
    {"query": "promocion obra nueva Madrid 2025 2026 entrega", "zone": "todas"},
    {"query": "nueva promocion viviendas Madrid comunidad desde", "zone": "todas"},
    {"query": "pisos obra nueva baratos Madrid zona norte este oeste", "zone": "todas"},
    # ── Promotoras y constructoras ─────────────────────────────────────
    {"query": "promotora inmobiliaria Madrid obra nueva promociones", "zone": "todas"},
    {"query": "constructora viviendas Madrid nuevas promociones 2025 2026", "zone": "todas"},
    {"query": "promotora pisos nuevos Madrid norte", "zone": "norte"},
    {"query": "promotora pisos nuevos Madrid este corredor henares", "zone": "este"},
    {"query": "promotora pisos nuevos Madrid oeste sierra", "zone": "oeste"},
    # ── VPO y vivienda protegida ───────────────────────────────────────
    {"query": "vivienda proteccion oficial VPO Madrid 2025 2026 solicitud", "zone": "todas"},
    {"query": "VPO Madrid norte este oeste nueva adjudicacion", "zone": "todas"},
    {"query": "vivienda protegida precio limitado VPPL Madrid", "zone": "todas"},
    {"query": "EMVS Madrid vivienda publica sorteo 2025 2026", "zone": "todas"},
    # ── Busquedas amplias ──────────────────────────────────────────────
    {"query": "comprar piso nuevo Madrid zona norte 2 3 habitaciones", "zone": "norte"},
    {"query": "comprar piso nuevo Madrid zona este 2 3 habitaciones", "zone": "este"},
    {"query": "comprar piso nuevo Madrid zona oeste 2 3 habitaciones", "zone": "oeste"},
    {"query": "residencial nuevo Madrid entrega 2025 2026 2027", "zone": "todas"},
    {"query": "listado promociones obra nueva Madrid actualizado", "zone": "todas"},
    {"query": "mejores cooperativas vivienda Madrid opiniones", "zone": "todas"},
    {"query": "donde comprar piso obra nueva Madrid precios cooperativa", "zone": "todas"},
    {"query": "vivienda cooperativa Madrid ahorro VPO joven primer piso", "zone": "todas"},
)
